# Generated by Django 4.0 on 2021-12-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_show_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
    ]
